# Constants for the display software for the
# Tetra Biodistributed Ventillator Splitter

NUMBER_OF_PATIENTS = 4
PRESSURE_SENSOR = "SPL06_007"
SENSIRION_SENSOR = "SFM3300"
MASS_AIRFLOW_SENSOR = "Mass Air Flow"  # TODO: find part no.

# These must be from the set {1, 2, 4, 8, 16, 32, 64, 128}
PRESSURE_SAMPLING_RATE = 1  # Hz
PRESSURE_OVERSAMPLING = 16
TEMPERATURE_SAMPLING_RATE = 1  # Hz
TEMPERATURE_OVERSAMPLING = 1

# Environment variables for testing off of hardware
SENSOR_QUANTITY = "SENSOR_QUANTITY"
ENOUGH_SENSORS = "ENOUGH_SENSORS"
TOO_MANY_SENSORS = "TOO_MANY_SENSORS"
NOT_ENOUGH_SENSORS = "NOT_ENOUGH_SENSORS"
